***Comparison of Different Classification Models with Accuracy Score***

# Importing the libraries

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Importing the Dataset

In [0]:
Dataset = pd.read_csv('breast-cancer-wisconsin-dataset.csv')
X = Dataset.iloc[:, 2:].values
Y = Dataset.iloc[:, 1].values
Dataset.head(8)

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN
5    843786         M  ...                  0.12440          NaN
6    844359         M  ...                  0.08368          NaN
7  84458202         M  ...                  0.11510          NaN

[8 rows x 33 columns]

# Taking care of missing data

In [0]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X)
X = imputer.transform(X)

#Encoding the Dependent Variable

In [0]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
Y = LE.fit_transform(Y)
print(Y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0
 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1
 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0
 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1
 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0
 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 0 1 0 0 1 

#Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 0)

#Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
SC = StandardScaler()
X_train = SC.fit_transform(X_train)
X_test = SC.transform(X_test)

# Training the K-NN model on the Training set

In [0]:
from sklearn.neighbors import KNeighborsClassifier
KKN = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
KKN.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

Making the Confusion Matrix and printing Accuracy score (KKN)

In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred1 = KKN.predict(X_test)
CM1 = confusion_matrix(Y_test, Y_pred1)
print(CM1, "\n")
accuracy_score(Y_test, Y_pred1)

[[67  0]
 [ 5 42]] 



0.956140350877193

# Training the Logistic Regression model on the Training set

In [0]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state = 0)
LR.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

Making the Confusion Matrix and printing Accuracy score (Logistic Regression)

In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred2 = LR.predict(X_test)
CM2 = confusion_matrix(Y_test, Y_pred2)
print(CM2, "\n")
accuracy_score(Y_test, Y_pred2)

[[65  2]
 [ 2 45]] 



0.9649122807017544

# Training the Naive Bayes model on the Training set

In [0]:
from sklearn.naive_bayes import GaussianNB
NB = GaussianNB()
NB.fit(X_train, Y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

Making the Confusion Matrix and printing Accuracy score (Naive Bayes)

In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred3 = NB.predict(X_test)
CM3 = confusion_matrix(Y_test, Y_pred3)
print(CM3, "\n")
accuracy_score(Y_test, Y_pred3)

[[61  6]
 [ 5 42]] 



0.9035087719298246

#Training the SVM model on the Training set

In [0]:
from sklearn.svm import SVC
SV = SVC(kernel = 'linear', random_state = 0)
SV.fit(X_train, Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

Making the Confusion Matrix and printing Accuracy score (Support Vector Machine)

In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred4 = SV.predict(X_test)
CM4 = confusion_matrix(Y_test, Y_pred4)
print(CM4, "\n")
accuracy_score(Y_test, Y_pred4)

[[66  1]
 [ 1 46]] 



0.9824561403508771

# Training the Kernel SVM model on the Training set

In [0]:
from sklearn.svm import SVC
KSV = SVC(kernel = 'rbf', random_state = 0)
KSV.fit(X_train, Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

Making the Confusion Matrix and printing Accuracy score (Kernel SVM)

In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred5 = KSV.predict(X_test)
CM5 = confusion_matrix(Y_test, Y_pred5)
print(CM5, "\n")
accuracy_score(Y_test, Y_pred5)

[[67  0]
 [ 2 45]] 



0.9824561403508771

# Training the Decision Tree Classification model on the Training set

In [0]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
DT.fit(X_train, Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

Making the Confusion Matrix and printing Accuracy score (Decision Tree)

In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred6 = DT.predict(X_test)
CM6 = confusion_matrix(Y_test, Y_pred6)
print(CM6, "\n")
accuracy_score(Y_test, Y_pred6)

[[62  5]
 [ 3 44]] 



0.9298245614035088

# Training the Random Forest Classification model on the Training set

In [0]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
RF.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

Making the Confusion Matrix and printing Accuracy score (Random Forest)

In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred7 = RF.predict(X_test)
CM7 = confusion_matrix(Y_test, Y_pred7)
print(CM7, "\n")
accuracy_score(Y_test, Y_pred7)

[[66  1]
 [ 2 45]] 



0.9736842105263158